Repository BCSDLab/KOALA_FRONT_END, pull requests merged in 2022-03, with the labels that each got.

#63 SNS 로그인 구현 작성
  package.json
  src/App.js
  src/api/index.js
  src/api/logined.js
  src/components/Auth/Login/Login.js
  src/components/Auth/Login/SNSLogin/LoginButton/GoogleLoginButton.js
  src/components/Auth/Login/SNSLogin/LoginButton/KakaoLoginButton.js
  src/components/Auth/Login/SNSLogin/LoginButton/NaverLoginButton.js
  src/components/Auth/Login/SNSLogin/LoginButton/SNSLoginButton.style.js
  src/components/Auth/Login/SNSLogin/OAuth/Google.js
  src/components/Auth/Login/SNSLogin/OAuth/Kakao.js
  src/components/Auth/Login/SNSLogin/OAuth/Naver.js
  src/components/Auth/Login/SNSLogin/OAuth/index.js
  src/components/Auth/Login/SNSLogin/ReactLogin/ReactNaverLogin.js
  src/components/Auth/index.js
  src/components/Auth/styles.js
  src/components/History/.gitkeep
  src/components/Shared/Cookies.js
  src/pages/OAuthPage.js
  src/store/auth.js
  src/store/index.js
Labels: Feature, Refactoring

#70 로딩 스피너 및 로딩 페이지 작성
  src/App.js
  src/components/Shared/LoadingSpinner.js
  src/pages/404.js
  src/pages/LodingPage.js
Labels: Feature, Style

#74 #68 히스토리/보관함 UI 스타일 수정
  src/api/index.js
  src/components/History/History/History.Style.js
  src/components/History/History/HistoryContent.js
  src/components/History/History/HistoryHeader.js
  src/components/History/History/HistoryPopup.js
  src/components/History/History/MobileMenuModal.js
  src/components/History/History/MobilePopUpModal.js
  src/components/History/Scrap/MobileScrapAlert.Style.js
  src/components/History/Scrap/MobileScrapAlert.js
  src/components/History/Scrap/Scrap.Style.js
  src/components/History/Scrap/ScrapContent.js
  src/pages/HistoryPage.js
Labels: Refactoring, Style
